<a href="https://colab.research.google.com/github/Pachuchka/python_for_analytics/blob/main/%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%20%D0%B4%D0%B0%D1%82%D0%B0%D1%84%D1%80%D0%B5%D0%B9%D0%BC%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Подключаем необходимые библиотеки, загружаем данные и создаём датафрейм

In [46]:
!pip install bootstrapped
from google.colab import drive
import pandas as pd
drive.mount
data = pd.read_csv('/content/sample_data/fifa_s2.csv')

data.head(10)

Requirement already satisfied: bootstrapped in /usr/local/lib/python3.10/dist-packages (0.0.2)
Requirement already satisfied: matplotlib>=1.5.3 in /usr/local/lib/python3.10/dist-packages (from bootstrapped) (3.7.1)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.10/dist-packages (from bootstrapped) (1.26.4)
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.10/dist-packages (from bootstrapped) (2.1.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.5.3->bootstrapped) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.5.3->bootstrapped) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.5.3->bootstrapped) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.5.3->bootstrapped) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.5.3->bootstrapped) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.5.3->bootstrapped) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.5.3->bootstrapped) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.5.3->bootstrapped) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.18.1->bootstrapped) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.18.1->bootstrapped) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=1.5.3->bootstrapped) (1.16.0)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,1179,G. Buffon,40,Italy,88,88,Paris Saint-Germain,4000.0,77,Right,4.0,1.0,GK,2018,01/01/2019,6.333333,203.0,7400.0
1,5479,Casillas,37,Spain,82,82,FC Porto,1500.0,10,Left,4.0,1.0,NaN,2015,01/01/2019,6.083333,185.0,3000.0
2,8205,Braga,35,Portugal,70,70,CD Aves,750.0,5,Right,1.0,3.0,LCM,2017,01/01/2019,5.916667,165.0,1600.0
3,9014,A. Robben,34,Netherlands,84,84,FC Bayern München,15500.0,110,Left,4.0,4.0,RM,2009,01/01/2019,5.916667,176.0,25600.0
4,19521,J. Ibehre,35,England,61,61,Cambridge United,120.0,2,Right,1.0,2.0,ST,2017,01/01/2019,6.333333,203.0,210.0
5,20209,Ricardo Costa,37,Portugal,74,74,CD Tondela,750.0,4,Right,2.0,2.0,LCB,2017,01/01/2019,6.000000,181.0,1600.0
6,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405,Right,5.0,5.0,ST,2018,01/01/2022,6.166667,183.0,127100.0
7,24630,Pepe Reina,35,Spain,83,83,Milan,6000.0,56,Right,3.0,1.0,GK,2018,NaN,6.166667,203.0,10200.0
8,27532,D. de Vries,37,Netherlands,66,66,Celtic,40.0,7,Right,1.0,1.0,GK,2016,01/01/2019,6.250000,212.0,72.0
9,45083,S. von Bergen,35,Switzerland,73,73,BSC Young Boys,950.0,12,Right,2.0,2.0,LCB,2013,01/01/2022,6.000000,174.0,1400.0

Выполним команду по удалению столбцов, содержащих одинаковые значения

In [47]:
data = data.T.drop_duplicates().T
data.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,1179,G. Buffon,40,Italy,88,88,Paris Saint-Germain,4000.0,77,Right,4.0,1.0,GK,2018,01/01/2019,6.333333,203.0,7400.0
1,5479,Casillas,37,Spain,82,82,FC Porto,1500.0,10,Left,4.0,1.0,NaN,2015,01/01/2019,6.083333,185.0,3000.0
2,8205,Braga,35,Portugal,70,70,CD Aves,750.0,5,Right,1.0,3.0,LCM,2017,01/01/2019,5.916667,165.0,1600.0
3,9014,A. Robben,34,Netherlands,84,84,FC Bayern München,15500.0,110,Left,4.0,4.0,RM,2009,01/01/2019,5.916667,176.0,25600.0
4,19521,J. Ibehre,35,England,61,61,Cambridge United,120.0,2,Right,1.0,2.0,ST,2017,01/01/2019,6.333333,203.0,210.0
5,20209,Ricardo Costa,37,Portugal,74,74,CD Tondela,750.0,4,Right,2.0,2.0,LCB,2017,01/01/2019,6.0,181.0,1600.0
6,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405,Right,5.0,5.0,ST,2018,01/01/2022,6.166667,183.0,127100.0
7,24630,Pepe Reina,35,Spain,83,83,Milan,6000.0,56,Right,3.0,1.0,GK,2018,NaN,6.166667,203.0,10200.0
8,27532,D. de Vries,37,Netherlands,66,66,Celtic,40.0,7,Right,1.0,1.0,GK,2016,01/01/2019,6.25,212.0,72.0
9,45083,S. von Bergen,35,Switzerland,73,73,BSC Young Boys,950.0,12,Right,2.0,2.0,LCB,2013,01/01/2022,6.0,174.0,1400.0

Столбцов, содержащих одинаковые значения не обнаружено

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2399 entries, 0 to 2398
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        2399 non-null   object
 1   Name                      2399 non-null   object
 2   Age                       2399 non-null   object
 3   Nationality               2392 non-null   object
 4   Overall                   2399 non-null   object
 5   Potential                 2399 non-null   object
 6   Club                      2158 non-null   object
 7   Value                     2142 non-null   object
 8   Wage                      2399 non-null   object
 9   Preferred Foot            2399 non-null   object
 10  International Reputation  2389 non-null   object
 11  Skill Moves               2393 non-null   object
 12  Position                  2378 non-null   object
 13  Joined                    2399 non-null   object
 14  Contract Valid Until      2126 non-null   object
 15  Height                    2399 non-null   object
 16  Weight                    2399 non-null   object
 17  Release Clause            2396 non-null   object
dtypes: object(18)
memory usage: 337.5+ KB

Статистика по незаполненным полям

In [49]:
data.isnull().sum()

ID                            0
Name                          0
Age                           0
Nationality                   7
Overall                       0
Potential                     0
Club                        241
Value                       257
Wage                          0
Preferred Foot                0
International Reputation     10
Skill Moves                   6
Position                     21
Joined                        0
Contract Valid Until        273
Height                        0
Weight                        0
Release Clause                3
dtype: int64

Преобразуем названия клубов к нижнему регистру, во избежания двоякости прочтения

In [50]:
data['Club'] = data['Club'].str.lower()
data.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,1179,G. Buffon,40,Italy,88,88,paris saint-germain,4000.0,77,Right,4.0,1.0,GK,2018,01/01/2019,6.333333,203.0,7400.0
1,5479,Casillas,37,Spain,82,82,fc porto,1500.0,10,Left,4.0,1.0,NaN,2015,01/01/2019,6.083333,185.0,3000.0
2,8205,Braga,35,Portugal,70,70,cd aves,750.0,5,Right,1.0,3.0,LCM,2017,01/01/2019,5.916667,165.0,1600.0
3,9014,A. Robben,34,Netherlands,84,84,fc bayern münchen,15500.0,110,Left,4.0,4.0,RM,2009,01/01/2019,5.916667,176.0,25600.0
4,19521,J. Ibehre,35,England,61,61,cambridge united,120.0,2,Right,1.0,2.0,ST,2017,01/01/2019,6.333333,203.0,210.0
5,20209,Ricardo Costa,37,Portugal,74,74,cd tondela,750.0,4,Right,2.0,2.0,LCB,2017,01/01/2019,6.0,181.0,1600.0
6,20801,Cristiano Ronaldo,33,Portugal,94,94,juventus,77000.0,405,Right,5.0,5.0,ST,2018,01/01/2022,6.166667,183.0,127100.0
7,24630,Pepe Reina,35,Spain,83,83,milan,6000.0,56,Right,3.0,1.0,GK,2018,NaN,6.166667,203.0,10200.0
8,27532,D. de Vries,37,Netherlands,66,66,celtic,40.0,7,Right,1.0,1.0,GK,2016,01/01/2019,6.25,212.0,72.0
9,45083,S. von Bergen,35,Switzerland,73,73,bsc young boys,950.0,12,Right,2.0,2.0,LCB,2013,01/01/2022,6.0,174.0,1400.0

In [51]:
data.drop_duplicates(subset=['ID'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2399 entries, 0 to 2398
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        2399 non-null   object
 1   Name                      2399 non-null   object
 2   Age                       2399 non-null   object
 3   Nationality               2392 non-null   object
 4   Overall                   2399 non-null   object
 5   Potential                 2399 non-null   object
 6   Club                      2158 non-null   object
 7   Value                     2142 non-null   object
 8   Wage                      2399 non-null   object
 9   Preferred Foot            2399 non-null   object
 10  International Reputation  2389 non-null   object
 11  Skill Moves               2393 non-null   object
 12  Position                  2378 non-null   object
 13  Joined                    2399 non-null   object
 14  Contract Valid Until      2126 non-null   object
 15  Height                    2399 non-null   object
 16  Weight                    2399 non-null   object
 17  Release Clause            2396 non-null   object
dtypes: object(18)
memory usage: 337.5+ KB

Удалим во всех столбцах пробелы в начале и в конце строки, дабы избежать двоякости прочтения

In [52]:
data = data.applymap(lambda x: x.strip() if isinstance(x, str) else x)
data.head(10)

<ipython-input-52-a64957a2536f>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data = data.applymap(lambda x: x.strip() if isinstance(x, str) else x)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,1179,G. Buffon,40,Italy,88,88,paris saint-germain,4000.0,77,Right,4.0,1.0,GK,2018,01/01/2019,6.333333,203.0,7400.0
1,5479,Casillas,37,Spain,82,82,fc porto,1500.0,10,Left,4.0,1.0,NaN,2015,01/01/2019,6.083333,185.0,3000.0
2,8205,Braga,35,Portugal,70,70,cd aves,750.0,5,Right,1.0,3.0,LCM,2017,01/01/2019,5.916667,165.0,1600.0
3,9014,A. Robben,34,Netherlands,84,84,fc bayern münchen,15500.0,110,Left,4.0,4.0,RM,2009,01/01/2019,5.916667,176.0,25600.0
4,19521,J. Ibehre,35,England,61,61,cambridge united,120.0,2,Right,1.0,2.0,ST,2017,01/01/2019,6.333333,203.0,210.0
5,20209,Ricardo Costa,37,Portugal,74,74,cd tondela,750.0,4,Right,2.0,2.0,LCB,2017,01/01/2019,6.000000,181.0,1600.0
6,20801,Cristiano Ronaldo,33,Portugal,94,94,juventus,77000.0,405,Right,5.0,5.0,ST,2018,01/01/2022,6.166667,183.0,127100.0
7,24630,Pepe Reina,35,Spain,83,83,milan,6000.0,56,Right,3.0,1.0,GK,2018,NaN,6.166667,203.0,10200.0
8,27532,D. de Vries,37,Netherlands,66,66,celtic,40.0,7,Right,1.0,1.0,GK,2016,01/01/2019,6.250000,212.0,72.0
9,45083,S. von Bergen,35,Switzerland,73,73,bsc young boys,950.0,12,Right,2.0,2.0,LCB,2013,01/01/2022,6.000000,174.0,1400.0

Удалим дубликаты по столбцам имя, возраст, национальность и клуб

In [53]:
data.info()
data = data.drop_duplicates(subset=['Name', 'Age', 'Nationality', 'Club'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2399 entries, 0 to 2398
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        2399 non-null   int64
 1   Name                      2399 non-null   object
 2   Age                       2399 non-null   int64
 3   Nationality               2392 non-null   object
 4   Overall                   2399 non-null   int64
 5   Potential                 2399 non-null   int64
 6   Club                      2158 non-null   object
 7   Value                     2142 non-null   float64
 8   Wage                      2399 non-null   int64
 9   Preferred Foot            2399 non-null   object
 10  International Reputation  2389 non-null   float64
 11  Skill Moves               2393 non-null   float64
 12  Position                  2378 non-null   object
 13  Joined                    2399 non-null   int64
 14  Contract Valid Until      2126 non-null   object
 15  Height                    2399 non-null   float64
 16  Weight                    2399 non-null   float64
 17  Release Clause            2396 non-null   float64
dtypes: float64(6), int64(6), object(6)
memory usage: 337.5+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 2395 entries, 0 to 2398
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        2395 non-null   int64
 1   Name                      2395 non-null   object
 2   Age                       2395 non-null   int64
 3   Nationality               2388 non-null   object
 4   Overall                   2395 non-null   int64
 5   Potential                 2395 non-null   int64
 6   Club                      2155 non-null   object
 7   Value                     2139 non-null   float64
 8   Wage                      2395 non-null   int64
 9   Preferred Foot            2395 non-null   object
 10  International Reputation  2385 non-null   float64
 11  Skill Moves               2389 non-null   float64
 12  Position                  2374 non-null   object
 13  Joined                    2395 non-null   int64
 14  Contract Valid Until      2123 non-null   object
 15  Height                    2395 non-null   float64
 16  Weight                    2395 non-null   float64
 17  Release Clause            2392 non-null   float64
dtypes: float64(6), int64(6), object(6)
memory usage: 355.5+ KB

были удалены 4 строки, как дублирующие

Создадим группы возрастов, определив их границы, затем классифицируем весь датафрейм по этим условиям

In [54]:
bins = [0, 20, 30, 36, 150]
labels = ['до 20', 'до 30', 'до 36', 'старше 36']
data['Age_group'] = pd.cut(data['Age'], bins=bins, labels=labels, include_lowest=True)
data.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,Age_group
0,1179,G. Buffon,40,Italy,88,88,paris saint-germain,4000.0,77,Right,4.0,1.0,GK,2018,01/01/2019,6.333333,203.0,7400.0,старше 36
1,5479,Casillas,37,Spain,82,82,fc porto,1500.0,10,Left,4.0,1.0,NaN,2015,01/01/2019,6.083333,185.0,3000.0,старше 36
2,8205,Braga,35,Portugal,70,70,cd aves,750.0,5,Right,1.0,3.0,LCM,2017,01/01/2019,5.916667,165.0,1600.0,до 36
3,9014,A. Robben,34,Netherlands,84,84,fc bayern münchen,15500.0,110,Left,4.0,4.0,RM,2009,01/01/2019,5.916667,176.0,25600.0,до 36
4,19521,J. Ibehre,35,England,61,61,cambridge united,120.0,2,Right,1.0,2.0,ST,2017,01/01/2019,6.333333,203.0,210.0,до 36
5,20209,Ricardo Costa,37,Portugal,74,74,cd tondela,750.0,4,Right,2.0,2.0,LCB,2017,01/01/2019,6.000000,181.0,1600.0,старше 36
6,20801,Cristiano Ronaldo,33,Portugal,94,94,juventus,77000.0,405,Right,5.0,5.0,ST,2018,01/01/2022,6.166667,183.0,127100.0,до 36
7,24630,Pepe Reina,35,Spain,83,83,milan,6000.0,56,Right,3.0,1.0,GK,2018,NaN,6.166667,203.0,10200.0,до 36
8,27532,D. de Vries,37,Netherlands,66,66,celtic,40.0,7,Right,1.0,1.0,GK,2016,01/01/2019,6.250000,212.0,72.0,старше 36
9,45083,S. von Bergen,35,Switzerland,73,73,bsc young boys,950.0,12,Right,2.0,2.0,LCB,2013,01/01/2022,6.000000,174.0,1400.0,до 36

Подсчитаем кол-во футболистов в каждой возрастной группе

In [55]:
age_group_counts = data['Age_group'].value_counts().to_frame('Count')
print(age_group_counts)

           Count
Age_group
до 30       1630
до 20        411
до 36        339
старше 36     15